schedule(Dates,Deadline) :-
    Dates = [Sa, Sb, Sc, Sd, Se, Sf, Sg],
    # DateRange = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
    numlist(0, Deadline, DateRange),
    member(Sa, DateRange),
    member(Sb, DateRange),
    member(Sc, DateRange),
    member(Sd, DateRange),
    member(Se, DateRange),
    member(Sf, DateRange),
    member(Sg, DateRange),

    Ea is Sa + 1,
    Eb is Sb + 3,
    Ec is Sc + 1,
    Ed is Sd + 2,
    Ee is Se + 2,
    Ef is Sf + 2,
    Eg is Sg + 3,

    Sb >= Ea,
    Sc >= Ea,
    Sd >= Eb,
    Se >= Eb,
    Sf >= Ec,
    Sf >= Ed,
    Sg >= Ee,
    Sg >= Ef.
